# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c5e10ebbeb6e801dff9a7faa8d416d8a5d13ebe6db62dd98b1e1eb732c5813d76e5a60e9937d45e782c6d04a457c77e36c2daf442f051f4af88634e9f0378eb

test:
  secret_key_base: 1447017fbf1afe36037d1108ad3587021b397dca79b0d2d57a9b8c9b37780b4d8b1f48978dbf776bebcfc6a7521f6db815550a9144dd2dbc1d7b19ed1d38e3bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
